export const SQUARE_SIZE = 40;
export const ALWAYS_OPEN_PADDING = 6;
export const ALWAYS_OPEN_TOP_PADDING = 20;
export const ALWAYS_OPEN =
  SQUARE_SIZE + ALWAYS_OPEN_PADDING + ALWAYS_OPEN_TOP_PADDING;
