import { themeColors } from './style';

export const playerColorKeys: (keyof typeof themeColors.light)[] = [
  'red',
  'yellow',
  'green',
  'blue',
  'purple',
  'white',
];

export const icons = [
  'check',
  'close',
  'exclamation',
  'comment-search-outline',
  'eye-outline',
  'eye-off-outline',
  'flash-outline',
  'alien-outline',
  'arm-flex-outline',
  'clock-outline',
  'flag-outline',
  'heart-outline',
  'heart-broken-outline',
  'star-outline',
  'alarm-light-outline',
  'police-badge-outline',
  'bullhorn-outline',
  'script-text-outline',
  'crown-outline',
  'paper-roll-outline',
  'medal-outline',
  'briefcase-variant-outline',
  'sheep',
  'bacteria-outline',
  'brain',
  'cow',
];

export const sheet = [
  {
    title: 'Numbers',
    data: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
  },
  {
    title: 'Letters',
    data: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
    ],
  },
];
